version: "3.9"

services:
  nginx_server:
    build:
      context: './nginx'
    image: docker-web/nginx_server:2023052201
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html:/var/www/html
      - /var/log/docker-web:/var/log
      - ./share/phpmyadmin:/usr/share/nginx/html/phpmyadmin
    container_name: "docker_web_nginx_server_container"

  php_fpm_server:
    build:
      context: "./php-fpm"
    image: docker-web/php8_fpm_server:2023052201
    # user: "${UID}:${GID}"
    container_name: "docker_web_php8_fpm_server_container"
    ports:
      - "9001:9001"
    volumes:
      - /var/www/html:/var/www/html
      - /var/log/docker-web:/var/log
      - ./share/phpmyadmin:/usr/share/nginx/html/phpmyadmin

  mysql_server:
    build:
      context: './mysql'
    image: docker-web/mysql_server:2023052201
    container_name: "docker_web_mysql_server_container"
    environment:
      - MYSQL_ROOT_PASSWORD=MotDePasseRoot
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
